#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Border
bspc config focused_border_color 			"#6c71c4"
bspc config normal_border_color 			"#073642"
bspc config active_border_color 			"#073642"

# Bar
~/.config/polybar/launch.sh --shades &
~/.config/polybar/shades/scripts/random.sh &
# Wallpaper

# Picom
picom -CGb &

# Nitrogen
nitrogen --restore &

# Systrays
nm-applet --indicator &
xfce4-power-manager & # If you are using notebook



